trigger:
  branches:
    include:
    - production
    - develop
    - feature/*
    exclude:
    - feature/*-WIP

variables:
  uiSource: '/frontend'
  uiBuild: $(uiSource)/build

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  workingDirectory: frontend
  displayName: 'npm install'
  
- script: npm build
  workingDirectory: frontend
  displayName: 'npm run build'
