# Generated by Django 3.2.7 on 2021-12-24 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resume", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="about",
            name="skill_years",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="List of general skills", max_length=25
                ),
                default="{3 years, 3 years, 3 years, 3 years, 3 years, 3 years}",
                size=None,
            ),
            preserve_default=False,
        )
    ]
