# Generated by Django 3.2.7 on 2021-12-25 15:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("resume", "0002_about_skill_years")]

    operations = [
        migrations.AlterField(
            model_name="about", name="body", field=wagtail.core.fields.RichTextField()
        )
    ]
