# Generated by Django 3.2.7 on 2022-01-10 19:52

import django.contrib.postgres.fields
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("resume", "0003_alter_about_body")]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="employer_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(help_text="List of employers id's"),
                default=[1, 2, 3, 4, 5],
                size=5,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projects",
            name="body",
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
