# Generated by Django 3.2.7 on 2021-11-06 12:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resume", "0004_auto_20211106_1331")]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="navigation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Text on navigation buttons", max_length=25
                ),
                size=4,
            ),
        )
    ]
