# Generated by Django 3.2.7 on 2022-02-05 16:46

import django.contrib.postgres.fields
from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [("resume", "0005_clusterdata")]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="skill_ratings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(default=1),
                default=resume.models.default_skill_ratings,
                size=6,
            ),
        )
    ]
