# Generated by Django 3.2.7 on 2022-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resume", "0005_clusterdata")]

    operations = [
        migrations.AlterField(
            model_name="clusterdata",
            name="x_dim",
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clusterdata",
            name="y_dim",
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clusterdata",
            name="z_dim",
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
