# Generated by Django 3.2.7 on 2021-11-06 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_experience_employment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='employment_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Position and employer name separated by @', max_length=100), size=5),
        ),
    ]
