# Generated by Django 3.2.7 on 2021-11-10 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resume", "0010_alter_experience_employment_title")]

    operations = [
        migrations.AddField(
            model_name="about",
            name="skills_columns",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="projects",
            name="skills_columns",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="experience",
            name="employment_duration",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="MONTH-YYYY - MONTH-YYYY or MONTH-YYYY                - present (LinkedIn-like notation)",
                    max_length=100,
                ),
                size=5,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="body",
            field=models.CharField(help_text="Description of project", max_length=750),
        ),
        migrations.AlterField(
            model_name="projects",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=25),
                help_text="List of skills to complete this project",
                size=4,
            ),
        ),
    ]
