# Generated by Django 3.2.7 on 2021-12-14 20:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resume", "0013_socials")]

    operations = [
        migrations.AddField(
            model_name="about",
            name="skill_ratings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(default=1),
                default=[3, 3, 3, 3, 3, 3],
                size=6,
            ),
        )
    ]
