# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Resume CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        shell: bash
        working-directory: backend
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash
        working-directory: backend
      # - name: Flake8 action
      #   uses: suo/flake8-github-action@v1
